In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
# DataFrame  oluşturma(kodlar)

stn_boy = np.random.randint(150,190,(10))
stn_kilo = np.random.randint(50,100,(10))
stn_no = np.random.randint(2100,2200,(10))

# pandas kütüphanesi, dictionary veri yapısı üzerine kurulur.
# pandas kütüphanesi ile excel ve sql'daki her şeyi yapabilir.

my_dict = {"ogr_no":stn_no,"ogr_boy":stn_boy,"ogr_kilo":stn_kilo}
my_df = pd.DataFrame.from_dict(my_dict)
my_df

ogr_no  ogr_boy  ogr_kilo
0    2180      161        80
1    2119      178        78
2    2149      174        96
3    2138      185        60
4    2156      168        58
5    2197      159        61
6    2198      178        51
7    2141      161        78
8    2176      173        83
9    2174      170        53

In [3]:
my_df.index

RangeIndex(start=0, stop=10, step=1)

In [4]:
my_df.index = ["ogrenci_1","ogrenci_2","ogrenci_3","ogrenci_4","ogrenci_5","ogrenci_6","ogrenci_7","ogrenci_8","ogrenci_9","ogrenci_10"]
my_df

ogr_no  ogr_boy  ogr_kilo
ogrenci_1     2180      161        80
ogrenci_2     2119      178        78
ogrenci_3     2149      174        96
ogrenci_4     2138      185        60
ogrenci_5     2156      168        58
ogrenci_6     2197      159        61
ogrenci_7     2198      178        51
ogrenci_8     2141      161        78
ogrenci_9     2176      173        83
ogrenci_10    2174      170        53

In [5]:
# DataFrame'ye yeni sütün ve değeler ekleme
stn_vize = np.random.randint(20,100,(10))
stn_final = np.random.randint(20,100,(10))

my_df["ogr_vize"] = stn_vize
my_df["ogr_final"] = stn_final
my_df

ogr_no  ogr_boy  ogr_kilo  ogr_vize  ogr_final
ogrenci_1     2180      161        80        27         35
ogrenci_2     2119      178        78        34         67
ogrenci_3     2149      174        96        94         55
ogrenci_4     2138      185        60        68         95
ogrenci_5     2156      168        58        77         33
ogrenci_6     2197      159        61        95         78
ogrenci_7     2198      178        51        45         24
ogrenci_8     2141      161        78        35         23
ogrenci_9     2176      173        83        73         67
ogrenci_10    2174      170        53        34         88

In [6]:
deger_vize = my_df["ogr_vize"].values
deger_final = my_df["ogr_final"].values

In [7]:
deger_vize

array([27, 34, 94, 68, 77, 95, 45, 35, 73, 34])

In [8]:
deger_final

array([35, 67, 55, 95, 33, 78, 24, 23, 67, 88])

In [9]:
deger_vize*2

array([ 54,  68, 188, 136, 154, 190,  90,  70, 146,  68])

In [10]:
deger_vize*0,5

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 5)

In [11]:
# ogr_gecti isimli bir key ekleyin
#bu key'in değerleri vize notlarının yüzde kırkı ile 
# final notlarının yüzde altısınının toplamı olacak 

In [12]:
deger_vize = my_df["ogr_vize"].values*0.40 
deger_final= my_df["ogr_final"].values*0.60 
deger_gecti = deger_vize+ deger_final
my_df["ogr_gecti"]=deger_gecti
my_df

ogr_no  ogr_boy  ogr_kilo  ogr_vize  ogr_final  ogr_gecti
ogrenci_1     2180      161        80        27         35       31.8
ogrenci_2     2119      178        78        34         67       53.8
ogrenci_3     2149      174        96        94         55       70.6
ogrenci_4     2138      185        60        68         95       84.2
ogrenci_5     2156      168        58        77         33       50.6
ogrenci_6     2197      159        61        95         78       84.8
ogrenci_7     2198      178        51        45         24       32.4
ogrenci_8     2141      161        78        35         23       27.8
ogrenci_9     2176      173        83        73         67       69.4
ogrenci_10    2174      170        53        34         88       66.4

In [13]:
my_df["durum"] = my_df["ogr_gecti"].values>50
my_df

ogr_no  ogr_boy  ogr_kilo  ogr_vize  ogr_final  ogr_gecti  durum
ogrenci_1     2180      161        80        27         35       31.8  False
ogrenci_2     2119      178        78        34         67       53.8   True
ogrenci_3     2149      174        96        94         55       70.6   True
ogrenci_4     2138      185        60        68         95       84.2   True
ogrenci_5     2156      168        58        77         33       50.6   True
ogrenci_6     2197      159        61        95         78       84.8   True
ogrenci_7     2198      178        51        45         24       32.4  False
ogrenci_8     2141      161        78        35         23       27.8  False
ogrenci_9     2176      173        83        73         67       69.4   True
ogrenci_10    2174      170        53        34         88       66.4   True

In [14]:
my_df["cinsiyet"] = "erkek"
my_df

ogr_no  ogr_boy  ogr_kilo  ogr_vize  ogr_final  ogr_gecti  durum  \
ogrenci_1     2180      161        80        27         35       31.8  False   
ogrenci_2     2119      178        78        34         67       53.8   True   
ogrenci_3     2149      174        96        94         55       70.6   True   
ogrenci_4     2138      185        60        68         95       84.2   True   
ogrenci_5     2156      168        58        77         33       50.6   True   
ogrenci_6     2197      159        61        95         78       84.8   True   
ogrenci_7     2198      178        51        45         24       32.4  False   
ogrenci_8     2141      161        78        35         23       27.8  False   
ogrenci_9     2176      173        83        73         67       69.4   True   
ogrenci_10    2174      170        53        34         88       66.4   True   

           cinsiyet  
ogrenci_1     erkek  
ogrenci_2     erkek  
ogrenci_3     erkek  
ogrenci_4     erkek  
ogrenci_5     erkek  
ogrenci_6     erkek  
ogrenci_7     erkek  
ogrenci_8     erkek  
ogrenci_9     erkek  
ogrenci_10    erkek

In [15]:
#istenilen özelliklere göre deger getirme
#tek sorguya göre 
my_df[my_df["ogr_vize"]<50]

ogr_no  ogr_boy  ogr_kilo  ogr_vize  ogr_final  ogr_gecti  durum  \
ogrenci_1     2180      161        80        27         35       31.8  False   
ogrenci_2     2119      178        78        34         67       53.8   True   
ogrenci_7     2198      178        51        45         24       32.4  False   
ogrenci_8     2141      161        78        35         23       27.8  False   
ogrenci_10    2174      170        53        34         88       66.4   True   

           cinsiyet  
ogrenci_1     erkek  
ogrenci_2     erkek  
ogrenci_7     erkek  
ogrenci_8     erkek  
ogrenci_10    erkek

In [16]:
#birden fazla sorguya göre deger çagırma
my_df[(my_df["ogr_vize"]<50) & (my_df["durum"]== True) & (my_df["ogr_boy"]>170)]

ogr_no  ogr_boy  ogr_kilo  ogr_vize  ogr_final  ogr_gecti  durum  \
ogrenci_2    2119      178        78        34         67       53.8   True   

          cinsiyet  
ogrenci_2    erkek

In [17]:
my_ds = sns.load_dataset("titanic")
my_ds

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [18]:
# yabancı bir veri seti görüğünüzde 
my_ds.describe()

survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [19]:
my_ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [20]:
sorgu = my_ds.pivot_table("survived",index="sex",columns="class",aggfunc=np.sum)

C:\Users\silan\AppData\Local\Temp\ipykernel_11956\152737770.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  sorgu = my_ds.pivot_table("survived",index="sex",columns="class",aggfunc=np.sum)
C:\Users\silan\AppData\Local\Temp\ipykernel_11956\152737770.py:1: FutureWarning: The provided callable <function sum at 0x000001BA132C48B0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  sorgu = my_ds.pivot_table("survived",index="sex",columns="class",aggfunc=np.sum)


In [21]:
# verileri kaydetme excel olarak

pd.DataFrame.to_excel(my_df,"my_df.xlsx")

In [23]:
pd.DataFrame.to_excel(sorgu,"my_ds_pivot_table.xlsx")

In [ ]:
!!